###
POST http://localhost:9000/api/v1/docentes HTTP/1.1
Content-Type: application/json

{
    "nombre": "abc",
    "apellido": "abc",
    "email": "abc",
    "codigo": "abc",
    "fecha": "abc",
    "contrasenia": "abc",
    "recontrasenia": "abc"
}

### 
GET http://localhost:9000/api/v1/docentes HTTP/1.1

//Busqueda por "_id"
###
GET http://localhost:9000/api/users/64eec850f769210673b03362 HTTP/1.1

//Actualiza por "_id"
###
PUT http://localhost:9000/api/users/64eec850f769210673b03362 HTTP/1.1
Content-Type: application/json

{
    "correo": "miguel.villegas2@unmsm.edu.pe",
    "contraseña": "54321"
}

//Eliminar por "_id"
###
DELETE http://localhost:9000/api/users/64eec850f769210673b03362 HTTP/1.1